app/tuimagen_lab/doctores/urls.py
from django.urls import path
from .views import buscar_doctor

urlpatterns = [
    path('buscar_doctor/', buscar_doctor, name='buscar_doctor'),
]

app/tuimagen_lab/trabajos/urls.py
from django.urls import path
from .views import seleccionar_tipo_trabajo, ver_trabajos_pendientes, ver_trabajos_terminados, terminar_trabajo, trabajos_por_pagar_por_doctor, trabajos_pagados_por_doctor, marcar_pagado
from fresado import views as fresado
from impresion3d import views as impresion3d
from escaneos_intraorales import views as escaner_intraoral

urlpatterns = [
    path('', seleccionar_tipo_trabajo, name='seleccionar_tipo_trabajo'),
    path('pendientes/', ver_trabajos_pendientes, name='trabajos_pendientes'),
    path('terminados/', ver_trabajos_terminados, name='trabajos_terminados'),
    path('trabajos-por-pagar/doctor/<int:doctor_id>/', trabajos_por_pagar_por_doctor, name='trabajos_por_pagar_por_doctor'),
    path('trabajos-pagados/doctor/<int:doctor_id>/', trabajos_pagados_por_doctor, name='trabajos_pagados_por_doctor'),
    # URLs para la creación de los trabajos
    path('crear-trabajo-fresado/', fresado.crear_trabajo_fresado, name='crear_trabajo_fresado'),
    path('crear-trabajo-impresion3d/', impresion3d.crear_trabajo_impresion3d, name='crear_trabajo_impresion3d'),
    path('crear-trabajo-escaneo-intraoral/', escaner_intraoral.crear_trabajo_escaneo_intraoral, name='crear_trabajo_escaneo_intraoral'),
    # URLs para el detalles de los trabajos
    path('detalle/fresado/<int:trabajo_id>', fresado.detalle_trabajo_fresado, name='detalle_trabajo_fresado'),
    path('detalle/impresion3d/<int:trabajo_id>', impresion3d.detalle_trabajo_impresion3d, name='detalle_trabajo_impresion3d'),
    path('detalle/escaneo_intraoral/<int:trabajo_id>/', escaner_intraoral.detalle_trabajo_escaneo_intraoral, name='detalle_trabajo_escaneo_intraoral'),
    # URLs para terminar un trabajo
    path('terminar_trabajo/', terminar_trabajo, name='terminar_trabajo'),
    #URLs para pagar los trabajos del doctor
    path('marcar-pagado/', marcar_pagado, name='marcar_pagado'),
]

app/tuimagen_lab/tuimagen_lab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(next_page='/'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('', include('trabajos.urls')),
    path('doctor/', include('doctores.urls')),
]

app/tuimagen_lab/trabajos/models.py
from django.db import models
from django.utils import timezone
from pacientes.models import Paciente
from doctores.models import Doctor

class Trabajo(models.Model):
    ESTADOS = [
        ('en_proceso', 'En proceso'),
        ('terminado', 'Terminado'),
    ]

    TIPOS = [
        ('fresado', 'Fresado'),
        ('impresion_3d', 'Impresión 3D'),
        ('escaneo_intraoral', 'Escaneo Intraoral'),
    ]

    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(default=timezone.now, editable=False)
    fecha_entrega = models.DateField()
    fecha_termino = models.DateField(null=True)
    estado = models.CharField(max_length=20, choices=ESTADOS, default='en_proceso')
    tipo_trabajo = models.CharField(max_length=20, choices=TIPOS)

    def __str__(self):
        return f'Trabajo {self.tipo_trabajo} para {self.paciente}'

class TrabajoDoctor(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='trabajos')
    trabajo = models.ForeignKey(Trabajo, on_delete=models.CASCADE)
    pagado = models.BooleanField(default=False)
    fecha_pago = models.DateField(null=True)

    def __str__(self):
        return f'{self.doctor.name} - {self.trabajo}'

app/tuimagen_lab/trabajos/forms.py
from django import forms
from .models import Trabajo

class DateInput(forms.DateInput):
    input_type = 'date'

class TrabajoForm(forms.ModelForm):
    con_maquillaje = forms.BooleanField(required=False, label='Con Maquillaje')
    
    class Meta:
        model = Trabajo
        fields = ['fecha_entrega']
        widgets = {
            'fecha_entrega': DateInput(),
        }

app/tuimagen_lab/trabajos/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from datetime import datetime, timedelta
from django.utils.dateparse import parse_date
from django.utils import timezone
from django.db.models import Count
from .models import Trabajo, TrabajoDoctor
from doctores.models import Doctor

def obtener_trabajos_doctor(doctor, fecha_desde=None, fecha_hasta=None, estado='terminado'):
    if fecha_desde and fecha_hasta:
        # Convertir las fechas de cadena a objetos de fecha
        fecha_desde = parse_date(fecha_desde)
        fecha_hasta = parse_date(fecha_hasta)

        # Convertir las fechas a naive datetimes al inicio y fin del día
        fecha_desde = datetime.combine(fecha_desde, datetime.min.time())
        fecha_hasta = datetime.combine(fecha_hasta, datetime.max.time())
        
        # Asegurarse de que las fechas son aware datetimes
        fecha_desde = timezone.make_aware(fecha_desde, timezone.get_current_timezone())
        fecha_hasta = timezone.make_aware(fecha_hasta, timezone.get_current_timezone())
    else:
        # Filtrar los trabajos del doctor en los últimos 30 días si no se proporcionan fechas
        ahora = timezone.now()
        hace_30_dias = ahora - timedelta(days=30)
        fecha_desde = hace_30_dias
        fecha_hasta = ahora

    trabajos_doctor = TrabajoDoctor.objects.filter(
        doctor=doctor,
        trabajo__fecha_termino__range=(fecha_desde, fecha_hasta),
        trabajo__estado=estado
    )

    return trabajos_doctor, fecha_desde, fecha_hasta


# Create your views here.
@login_required
def seleccionar_tipo_trabajo(request):
    tipos_trabajo = Trabajo.TIPOS
    return render(request, 'trabajos/menu.html', {'tipos': tipos_trabajo})

@login_required
def ver_trabajos_pendientes(request):
    ESTADO = 'en_proceso'
    trabajos = Trabajo.objects.filter(estado=ESTADO)
        
    total_trabajos = trabajos.values('tipo_trabajo').annotate(total=Count('tipo_trabajo'))
    
    # cambiar los valores del nombre de los tipos de trabajo
    TIPOS_DICT = {key: value for key, value in Trabajo.TIPOS}
    # Reemplazar 'tipo_trabajo' en el queryset
    for item in total_trabajos:
        item['tipo_trabajo'] = TIPOS_DICT.get(item['tipo_trabajo'], item['tipo_trabajo'])
  
    return render(request, 'trabajos/listar_trabajos.html', {'trabajos': trabajos, 'total_trabajos': total_trabajos, 'estado': ESTADO})

@login_required
def ver_trabajos_terminados(request):
    ESTADO = 'terminado'

    # Obtener fechas desde el formulario
    fecha_desde = request.GET.get('fecha_desde')
    fecha_hasta = request.GET.get('fecha_hasta')

    if fecha_desde and fecha_hasta:
        # Convertir las fechas de cadena a objetos de fecha
        fecha_desde = parse_date(fecha_desde)
        fecha_hasta = parse_date(fecha_hasta)

        # Asegurarse de que la fecha_hasta incluye todo el día
        fecha_hasta = fecha_hasta + timedelta(days=1)

        # Filtrar los trabajos por las fechas proporcionadas
        trabajos = Trabajo.objects.filter(estado=ESTADO, fecha_termino__range=(fecha_desde, fecha_hasta))
    else:
        # Filtrar los trabajos terminados en los últimos 30 días si no se proporcionan fechas
        hace_30_dias = datetime.now() - timedelta(days=30)
        trabajos = Trabajo.objects.filter(estado=ESTADO, fecha_termino__gte=hace_30_dias)

    # Obtener el total de trabajos agrupados por tipo de trabajo
    total_trabajos = trabajos.values('tipo_trabajo').annotate(total=Count('tipo_trabajo'))
    
    # cambiar los valores del nombre de los tipos de trabajo
    TIPOS_DICT = {key: value for key, value in Trabajo.TIPOS}
    # Reemplazar 'tipo_trabajo' en el queryset
    for item in total_trabajos:
        item['tipo_trabajo'] = TIPOS_DICT.get(item['tipo_trabajo'], item['tipo_trabajo'])

    return render(request, 'trabajos/listar_trabajos.html', {'trabajos': trabajos, 'total_trabajos': total_trabajos, 'estado': ESTADO})
    

@login_required
@require_POST
@csrf_exempt
def terminar_trabajo(request):
    ESTADO = 'terminado'
    trabajo_id = request.POST.get('id')
    trabajo = get_object_or_404(Trabajo, id=trabajo_id)
    
    if trabajo.estado != ESTADO:
        trabajo.estado = ESTADO
        trabajo.fecha_termino = timezone.now()
        trabajo.save()
        return JsonResponse({'success': True})
    return JsonResponse({'success': False, 'error': 'El trabajo ya está terminado'})

@login_required
def trabajos_por_pagar_por_doctor(request, doctor_id):
    doctor = get_object_or_404(Doctor, id=doctor_id)
    
    fecha_desde = request.GET.get('fecha_desde')
    fecha_hasta = request.GET.get('fecha_hasta')

    trabajos_doctor, fecha_desde, fecha_hasta = obtener_trabajos_doctor(doctor, fecha_desde, fecha_hasta)
    # filtra solo por los trabajos no pagos
    trabajos_doctor = trabajos_doctor.filter(pagado=False)

    context = {
        'doctor': doctor,
        'trabajos_doctor': trabajos_doctor,
        'fecha_desde': fecha_desde.strftime('%d-%m-%Y') if fecha_desde else '',
        'fecha_hasta': fecha_hasta.strftime('%d-%m-%Y') if fecha_hasta else '',
        'pagados': False
    }

    return render(request, 'trabajos/trabajos_por_doctor.html', context)

@login_required
def trabajos_pagados_por_doctor(request, doctor_id):
    doctor = get_object_or_404(Doctor, id=doctor_id)
    
    fecha_desde = request.GET.get('fecha_desde')
    fecha_hasta = request.GET.get('fecha_hasta')

    trabajos_doctor, fecha_desde, fecha_hasta = obtener_trabajos_doctor(doctor, fecha_desde, fecha_hasta)
    # filtra solo por los trabajos no pagos
    trabajos_doctor = trabajos_doctor.filter(pagado=True)

    context = {
        'doctor': doctor,
        'trabajos_doctor': trabajos_doctor,
        'fecha_desde': fecha_desde.strftime('%d-%m-%Y') if fecha_desde else '',
        'fecha_hasta': fecha_hasta.strftime('%d-%m-%Y') if fecha_hasta else '',
        'pagados': True
    }

    return render(request, 'trabajos/trabajos_por_doctor.html', context)

@csrf_exempt
def marcar_pagado(request):
    if request.method == 'POST':
        doctor_name = request.POST.get('doctorName')
        trabajos_ids = request.POST.getlist('trabajosIds[]')
        
        doctor = get_object_or_404(Doctor, name=doctor_name)
        trabajos = TrabajoDoctor.objects.filter(trabajo__id__in=trabajos_ids, doctor=doctor)
        
        trabajos.update(pagado=True, fecha_pago=timezone.now())

        return JsonResponse({'message': 'Trabajos marcados como pagados exitosamente'})
    return JsonResponse({'error': 'Método no permitido'}, status=405)

app/tuimagen_lab/templates/trabajos/buscar_doctor.html
{% extends "base.html" %}

{% block title %}Buscar Doctor{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Buscar Doctor</h6>
                </div>
                <div class="card-body">
                    {% if messages %}
                        <div class="alert alert-danger" role="alert">
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        </div>
                    {% endif %}
                    <form method="post" action="{% url 'buscar_doctor' %}?pagado={{ pagado|yesno:"true,false" }}">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <input type="text" list="datalistDoctores" class="form-control" id="nombre_doctor" name="nombre_doctor" placeholder="Nombre del Doctor" required>
                            <label for="nombre_doctor">Nombre del Doctor</label>
                            <datalist id="datalistDoctores">
                            {% for doctor in lista_doctores %}
                                <option value="{{ doctor.name }}">
                            {% endfor %}
                            </datalist>
                        </div>
                        <input type="hidden" name="pagado" value="{{ pagado|yesno:"true,false" }}">
                        <button type="submit" class="btn btn-primary w-100">Buscar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/tuimagen_lab/templates/trabajos/listar_trabajos.html
{% extends "base.html" %}

{% load static %}
{% block title %}Listado de Trabajos{% endblock %}

{% block head %}

<!-- Aquí puedes añadir estilos o scripts específicos para esta vista -->
     <!-- Custom styles for this page -->
     <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {% if total_trabajos.0 %}
        <div class="col-md-3 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {{total_trabajos.0.tipo_trabajo}}
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{total_trabajos.0.total}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-tv fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% if total_trabajos.1 %}
        <div class="col-md-3 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {{total_trabajos.1.tipo_trabajo}}
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{total_trabajos.1.total}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-tooth fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}

        {% if total_trabajos.2 %}
        <div class="col-md-3 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {{total_trabajos.2.tipo_trabajo}}
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{total_trabajos.2.total}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-teeth-open fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="col-md-3 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if estado == 'en_proceso' %}
                                Trabajos Pendientes
                                {% elif estado == 'terminado' %}
                                Trabajos Terminados
                                {% endif %}
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{trabajos.count}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-briefcase fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        {% if estado == 'terminado' %}
        <button type="button" class="btn btn-primary mb-4" data-bs-toggle="modal" data-bs-target="#filtroFechasModal_trabajoTerminados">
            <i class="fa-solid fa-filter"></i>
            Buscar por Fecha
        </button>
        {% endif %}

        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>N°</th>
                    <th>Nombre del Paciente</th>
                    <th>Nombre del Dentista</th>
                    <th>Fecha a Entregar</th>
                    {% if estado == 'terminado' %}
                        <th>Fecha de Termino</th>
                    {% endif %}
                    <th>Tipo</th>
                    <th>Detalle</th>
                    {% if estado == 'en_proceso' %}
                    <th>Terminar</th>
                    {% endif %}
                    
                </tr>
            </thead>
            <tbody>
                {% for trabajo in trabajos %}
                    <tr>
                        <td>{{trabajo.id}}</td>
                        <td>{{ trabajo.paciente.name }}</td>
                        <td>{{ trabajo.doctor.name }}</td>
                        <td>{{ trabajo.fecha_entrega }}</td>
                        {% if estado == 'terminado' %}
                        <td> {{trabajo.fecha_termino}} </td>
                        {% endif %}
                        <td class="text-center align-middle">
                            {% if trabajo.tipo_trabajo == 'fresado' %}
                            <span class="badge bg-success ">{{trabajo.get_tipo_trabajo_display}}</span>
                            {% elif trabajo.tipo_trabajo == 'impresion_3d' %}
                            <span class="badge bg-info ">{{trabajo.get_tipo_trabajo_display}}</span>
                            {% elif trabajo.tipo_trabajo == 'escaneo_intraoral' %}
                            <span class="badge bg-warning ">{{trabajo.get_tipo_trabajo_display}}</span>
                            {%endif%}
                        </td>
                        <td>
                            <a href="#" class="btn btn-outline-primary btn-icon-split trabajo-{{trabajo.tipo_trabajo}}" data-bs-toggle="modal" data-bs-target="#{{trabajo.tipo_trabajo}}" data-id="{{ trabajo.id }}">
                                <span class="icon text-white-50">
                                    <i class="fa-regular fa-eye fa-fade fa-xs primary" style="color: #707070;"></i>
                                </span>
                                <span class="text">Detalle</span>
                            </a>
                            
                            
                        </td>
                        {% if estado == 'en_proceso' %}
                        <td>
                            <button class="btn btn-outline-success btn-terminar-trabajo" data-id="{{ trabajo.id }}">
                                Terminar
                            </button>
                        </td>
                        {% endif %}

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>

{% comment %} modales {% endcomment %}
{% include "trabajos/modals/impresion_3d.html" %}
{% include "trabajos/modals/fresado.html" %}
{% include "trabajos/modals/escaneo_intraoral.html" %}
{% include "trabajos/modals/buscar_por_fecha_terminados.html" %}

{% endblock %}

{% block scripts %}
    <!-- Page level plugins -->
    <script src="{% static "vendor/datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "vendor/datatables/dataTables.bootstrap4.min.js" %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static "js/datatable.js" %}"></script>
    <script src="{% static "js/detalle_trabajo.js" %}"></script>
    <script src="{% static "js/terminar_trabajo.js" %}"></script>
{% endblock %}

app/tuimagen_lab/templates/trabajos/pdf_trabajos_por_doctor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .header, .footer {
            width: 100%;
            text-align: center;
            position: fixed;
        }
        .header {
            top: 0px;
        }
        .footer {
            bottom: 0px;
        }
        .pagenum:before {
            content: counter(page);
        }
        .content {
            margin-top: 50px;
            margin-bottom: 50px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 8px;
            border: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Trabajos de {{ doctor.name }}</h1>
        <p>Desde: {{ fecha_desde }} Hasta: {{ fecha_hasta }}</p>
    </div>
    <div class="content">
        <table>
            <thead>
                <tr>
                    <th>N°</th>
                    <th>Nombre del Paciente</th>
                    <th>Fecha de Entrega</th>
                    <th>Tipo de Trabajo</th>
                    <th>Estado</th>
                    <th>Pagado</th>
                </tr>
            </thead>
            <tbody>
                {% for trabajo_doctor in trabajos_doctor %}
                    <tr>
                        <td>{{ trabajo_doctor.trabajo.id }}</td>
                        <td>{{ trabajo_doctor.trabajo.paciente.name }}</td>
                        <td>{{ trabajo_doctor.trabajo.fecha_entrega }}</td>
                        <td>{{ trabajo_doctor.trabajo.get_tipo_trabajo_display }}</td>
                        <td>{{ trabajo_doctor.trabajo.get_estado_display }}</td>
                        <td>{{ trabajo_doctor.pagado|yesno:"Sí,No" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="footer">
        Página <span class="pagenum"></span>
    </div>
</body>
</html>

app/tuimagen_lab/templates/trabajos/trabajos_por_doctor.html
{% extends "base.html" %}
{% load static %}
{% block title %}Trabajos de {{ doctor.name }}{% endblock %}

{% block head %}

<!-- Aquí puedes añadir estilos o scripts específicos para esta vista -->
     <!-- Custom styles for this page -->
     <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row mb-4">
        <div class="col-md-3 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Trabajos de
                            </div>
                            <div id="nombreDoctor" class="h5 mb-0 font-weight-bold text-gray-800">{{doctor.name}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-address-card fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3 mb-4 ml-auto">
            <div class="card border-left-secondary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Trabajos Terminados
                            </div>
                            <div class="font-weight-bold text-secondary text-uppercase mb-1">
                                Desde: <span id="fecha_desde" class="text-primary">{{fecha_desde}}</span>
                            </div>
                            <div class=" font-weight-bold text-secondary text-uppercase mb-1">
                                Hasta: <span id="fecha_hasta" class="text-primary" >{{fecha_hasta}}</span>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <div class="d-flex justify-content-between mb-4">
            <button type="button" class="btn btn-primary w-25" data-bs-toggle="modal" data-bs-target="#filtroFechasModal_trabajoDoctores">
                <i class="fa-solid fa-filter"></i>
                Buscar por Fecha
            </button>
            {% if not pagados %}
            <button id="marcarPagado" class="btn btn-success w-25">
                <i class="fa-solid fa-check"></i>
                Marcar como Pagado
            </button>
            {% endif %}
            <div class="btn-group w-25">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa-solid fa-file"></i> Exportar
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#" id="generateExcel"><i class="fa-solid fa-file-excel"></i> Excel</a>
                    <a class="dropdown-item" href="#" id="generatePDF"><i class="fa-solid fa-file-pdf"></i> PDF</a>
                </div>
            </div>
        </div>
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>N°</th>
                    <th>Nombre del Paciente</th>
                    {% if pagados %}
                    <th>Fecha de Pago</th>
                    {% else  %}
                    <th>Fecha de Entrega</th>
                    {% endif %}
                    <th>Tipo de Trabajo</th>
                    <th>Estado</th>
                    <th>Pagado</th>
                </tr>
            </thead>
            <tbody>
                {% for trabajo_doctor in trabajos_doctor %}
                    <tr>
                        <td>{{ trabajo_doctor.trabajo.id }}</td>
                        <td>{{ trabajo_doctor.trabajo.paciente.name }}</td>
                        {% if pagados %}
                        <td>{{ trabajo_doctor.fecha_pago }}</td>
                        {% else %}
                        <td>{{ trabajo_doctor.trabajo.fecha_entrega }}</td>
                        {% endif %}
                        <td>{{ trabajo_doctor.trabajo.get_tipo_trabajo_display }}</td>
                        <td>{{ trabajo_doctor.trabajo.get_estado_display }}</td>
                        <td>{{ trabajo_doctor.pagado|yesno:"Sí,No" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% include "trabajos/modals/buscar_por_fecha_doctores.html" %}
{% endblock %}

{% block scripts %}
    <!-- Page level plugins -->
    <script src="{% static "vendor/datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "vendor/datatables/dataTables.bootstrap4.min.js" %}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.16.9/xlsx.full.min.js"></script>

    <!-- jsPDF desde CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.3.1/jspdf.umd.min.js"></script>
    
    <!-- jsPDF autoTable desde CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.13/jspdf.plugin.autotable.min.js"></script>
    <!-- Page level custom scripts -->
    <script src="{% static "js/datatable.js" %}"></script>
    <script src="{% static "js/generate_pdf.js" %}"></script>
    <script src="{% static "js/generate_excel.js" %}"></script>
    <script src="{% static "js/marcar_trabajos_pagados.js" %}"></script>

{% endblock %}